"""Update database schema

Revision ID: a94131e7d3e2
Revises: 30a41aa47440
Create Date: 2023-06-17 17:41:03.445122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94131e7d3e2'
down_revision = '30a41aa47440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('is_below_expected_calories')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_daily_calories', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('expected_daily_calories')

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_below_expected_calories', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
